/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetMarket__factory } from "./BetMarket__factory";
export { MockERC20__factory } from "./MockERC20__factory";
